# Site settings
author: Catherine Gloria
title: Coding Creatively
header-img: img/home-bg.png
email: catherinegloria@gmail.com
copyright_name: Catherine Gloria
description: > # this means to ignore newlines until "baseurl:"
  A singing coder aspiring to build programs for youth
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cglorious

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
